export const REQUEST_DICTIONARY = 'REQUEST_DICTIONARY';
export const REQUEST_DICTIONARY_PENDING = 'REQUEST_DICTIONARY_PENDING';
export const REQUEST_DICTIONARY_SUCCESS = 'REQUEST_DICTIONARY_SUCCESS';
export const REQUEST_DICTIONARY_ERROR = 'REQUEST_DICTIONARY_ERROR';
export const SET_THEME = 'SET_THEME';
